---
# roles/init_k8s/tasks/main.yml
- name: Initialize kubeadm
  ansible.builtin.include_tasks: init_kubeadm.yml

- name: Deploy the CNI(Calico)
  ansible.builtin.include_tasks: deploy_calico.yml

- name: Join the Worker Node
  ansible.builtin.include_tasks: join_worker.yml
