---
# roles/install_k8s/tasks/install_container-d.yml
# Docker 저장소에 있는 containerd 설치
- name: Install required packages for container runtime
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages }}"

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker GPG key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  ansible.builtin.shell: |
    echo "deb [arch={{ arch_mapping_var[ansible_facts['architecture']] }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Update apt cache
  ansible.builtin.package:
    update_cache: yes

- name: Install containerd.io package
  ansible.builtin.package:
    name: containerd.io
    state: present
    update_cache: yes

- name: Generate default containerd config
  ansible.builtin.shell: |
    containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1

- name: Modify containerd config for SystemdCgroup
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: "SystemdCgroup = false"
    replace: "SystemdCgroup = true"

- name: Restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: Enable containerd service on boot
  ansible.builtin.systemd:
    name: containerd
    enabled: yes