---
# role/install_k8s/tasks/main.yml
- name: Synchronize_ntp
  ansible.builtin.include_tasks: timesync.yml

- name: Configure the Node
  ansible.builtin.include_tasks: configure.yml
# swapoff -a swap 메모리 모드 비활성화

- name: Install Containerd
  ansible.builtin.include_tasks: install_container-d.yml

- name: Install kubeadm, kubectl, kubelet
  ansible.builtin.include_tasks: install_kube.yml
